### ISSUE TITLE
Replacing files with drag'n'drop does not trigger modified event

### ISSUE THREAD

**Issue by jone** [4teamwork/ftw.file#37]
When a file is replaced with drag'n'drop, a modified event should be fired so that the catalog is reindexed and other subscribers are notified.

**Comment by jone** [comment]
@Tschanzt please verify / fix :wink:

**Comment by Tschanzt** [comment]
@jone Well, The Archetypes ObjectEdited isn't fired but the zope.lifecycle event is. The Plone documentation(http://docs.plone.org/develop/addons/components/events.html#modified-events) states that ObjectEdited is usually called after an object reindex. Should it be fired manually?

**Comment by jone** [comment]
@Tschanzt the lifecycle event is quite good already, I think it wasn't fired when I created this ticket.
Can you verify, that when replacing a file, it's modified date index / metadata is changed to the current time in the catalog? If this happens I think we don't need to change anything..

**Comment by Tschanzt** [comment]
@jone As far as i can se it is updated.
