### ISSUE TITLE
Fix Plone 4.3.7 test errors

### ISSUE THREAD

**Issue by jone** [4teamwork/ftw.file#53]
Plone 4.3.7 has been released, now we have errors in our tests.

There are errors when [testing the available scales](https://github.com/4teamwork/ftw.file/blob/3111e6aa29b09ff51d902588766a7f2d1c851ce1/ftw/file/tests/test_fields.py#L20-L26):
```python
Failure in test test_available_sizes (ftw.file.tests.test_fields.TestFieldFunctions)
Traceback (most recent call last):
  File "/var/lib/jenkins/zope/eggs/unittest2-0.5.1-py2.7.egg/unittest2/case.py", line 340, in run
    testMethod()
  File "/var/lib/jenkins/jobs/ftw.file-master-test-plone-4.3.x.cfg/workspace/ftw/file/tests/test_fields.py", line 25, in test_available_sizes
    self.assertFalse(expected.symmetric_difference(sizes), "The Available"
  File "/var/lib/jenkins/zope/eggs/unittest2-0.5.1-py2.7.egg/unittest2/case.py", line 421, in assertFalse
    raise self.failureException(msg)
AssertionError: set(['colorbox']) is not False : The Available Sizes don't meet the expectations
```
(from https://jenkins.4teamwork.ch/job/ftw.file-master-test-plone-4.3.x.cfg/1037/console)

This test was added in https://github.com/4teamwork/ftw.file/pull/49.

I think the problem may be because default scales may have been removed in Plone 4.3.7, not verified. We should not rely on having default scales in that case.

@Tschanzt Do you remember why this test exist? Can we rewrite it somehow?
It would be great if you could take a look at that and propose a solution in order to make the tests green again :wink:

**Comment by Tschanzt** [comment]
Since I had to ensure that the field of ftw.file provides the identical functionality as the original ImageField this test was added to check that all scales are provided. Since the new ftw.colorbox release adds a new scale the test fails. But the Implementation has changed since the test was added. We now Inherit from the imagingmixin again and therefore I think it should be safe to remove it.

**Comment by tschanzt** [comment]
I think this is fixed.
